export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  PRINCIPAL: 'principal',
  TEACHER: 'teacher',
  STUDENT: 'student',
  PARENT: 'parent',
  STAFF: 'staff'
};

export const ROLE_ALIASES = {
  superadmin: ROLES.SUPER_ADMIN,
  super_admin: ROLES.SUPER_ADMIN,
  'Super Admin': ROLES.SUPER_ADMIN,
  admin: ROLES.ADMIN,
  principal: ROLES.PRINCIPAL,
  teacher: ROLES.TEACHER,
  student: ROLES.STUDENT,
  parent: ROLES.PARENT,
  staff: ROLES.STAFF
};

export const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: 100,
  [ROLES.ADMIN]: 80,
  [ROLES.PRINCIPAL]: 70,
  [ROLES.TEACHER]: 50,
  [ROLES.STAFF]: 40,
  [ROLES.PARENT]: 20,
  [ROLES.STUDENT]: 10
};

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  USERS_MANAGE: 'users:manage',
  STUDENTS_READ: 'students:read',
  STUDENTS_WRITE: 'students:write',
  TEACHERS_READ: 'teachers:read',
  TEACHERS_WRITE: 'teachers:write',
  CLASSES_MANAGE: 'classes:manage',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_WRITE: 'attendance:write',
  GRADES_READ: 'grades:read',
  GRADES_WRITE: 'grades:write',
  REPORTS_READ: 'reports:read',
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_WRITE: 'notifications:write',
  AUDIT_READ: 'audit:read',
  SETTINGS_MANAGE: 'settings:manage'
};

export const DEFAULT_ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_WRITE,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.TEACHERS_WRITE,
    PERMISSIONS.CLASSES_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.GRADES_WRITE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE
  ],
  [ROLES.PRINCIPAL]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.CLASSES_MANAGE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.GRADES_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.NOTIFICATIONS_READ
  ],
  [ROLES.PARENT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.NOTIFICATIONS_READ
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.NOTIFICATIONS_READ
  ]
};

export const normalizeRole = (role) => ROLE_ALIASES[role] || String(role || '').toLowerCase();

export const permissionsForRoles = (roles = []) => {
  const normalizedRoles = roles.map(normalizeRole);
  return [...new Set(normalizedRoles.flatMap((role) => DEFAULT_ROLE_PERMISSIONS[role] || []))];
};
